CREATE TABLE students (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  last_name VARCHAR(30) NOT NULL,
  first_name VARCHAR(30) NOT NULL,
  isikukood VARCHAR(11) NOT NULL UNIQUE,
  grade INT(1) NOT NULL,
  email VARCHAR(20) NOT NULL,
  message VARCHAR(250),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

